server:
  port: 8080
  servlet:
    context-path: /rrapp
spring:
  application:
    name: rrapp
  redis:
    port: 6379
    host: 111.230.47.161
    password: Asdfg12/
  datasource:
    name: test
    url: jdbc:mysql://111.230.47.161:3306/${spring.datasource.db}?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    db: rr
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapperLocations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.lzh.*.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl